version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for the Frontend Client (React/Vite)
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"

  # Maintain dependencies for the Backend Server (Express/Node)
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
